language: python
python:
  - "3.7"

before_install:
  - sudo apt-get install build-essential git
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - git clone https://github.com/xianyi/OpenBLAS && cd OpenBLAS && sudo make && sudo make install
  - ls /opt/OpenBLAS/lib
  - sudo ln -s /opt/OpenBLAS/lib/libopenblas_haswellp-*.so /usr/lib/libblas.so.3
  - sudo ln -s /opt/OpenBLAS/lib/libopenblas_haswellp-*.so /usr/lib/liblapack.so.3

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script:
  - python -m unittest tests/apitest.py
