language: python
python:
  - "3.7"

before_install:
  - sudo apt-get install build-essential git
  - sudo apt-get install libopenblas-dev

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script:
  - python -m unittest tests/apitest.py
